import Link from "next/link";

export default function HomePage() {
  return (
    <main className="static-page">
      <section className="static-hero">
        <span className="neo-badge primary font-mono" style={{ marginBottom: 16, fontSize: "0.9rem", transform: "rotate(-1deg)" }}>
          ⚡ CLOUD SECURED DATA SHELTER
        </span>
        <h1>
          THE ULTRALIGHT <br />
          <span style={{ backgroundColor: "var(--color-primary)", padding: "0 10px", border: "3px solid #000", display: "inline-block", transform: "rotate(1deg)", boxShadow: "3px 3px 0px 0px #000" }}>
            PHOTO VAULT
          </span>
        </h1>
        <p>
          A static-export front end that uses Lambda for Cognito auth, S3 signed URLs, and DynamoDB metadata, while keeping the same neo-brutalist visual language as the original app.
        </p>

        <div className="static-row">
          <Link href="/dashboard" className="neo-btn primary animate-subtle" style={{ fontSize: "1.1rem", padding: "16px 32px" }}>
            ENTER PHOTO VAULT 🗄️
          </Link>
          <Link href="/login" className="neo-btn font-mono" style={{ fontSize: "1.1rem", padding: "14px 28px" }}>
            LOG_IN.COM
          </Link>
          <Link href="/register" className="neo-btn accent font-mono" style={{ fontSize: "1.1rem", padding: "14px 28px" }}>
            REGISTER_USER()
          </Link>
        </div>
      </section>

      <div className="static-grid">
        <div className="neo-box hoverable">
          <div className="neo-badge primary" style={{ marginBottom: 12 }}>IDENTITY</div>
          <h3 style={{ fontSize: "1.4rem" }}>Amazon Cognito Auth</h3>
          <p style={{ fontSize: "0.95rem", lineHeight: 1.4 }}>Accounts are managed from Lambda-backed Cognito workflows. The static site never stores AWS secrets.</p>
        </div>

        <div className="neo-box hoverable">
          <div className="neo-badge secondary" style={{ marginBottom: 12 }}>ENCRYPTION</div>
          <h3 style={{ fontSize: "1.4rem" }}>AWS KMS Data Armor</h3>
          <p style={{ fontSize: "0.95rem", lineHeight: 1.4 }}>Uploads are signed server-side and stored in private S3 with KMS-backed encryption.</p>
        </div>

        <div className="neo-box hoverable">
          <div className="neo-badge accent" style={{ marginBottom: 12 }}>ISOLATION</div>
          <h3 style={{ fontSize: "1.4rem" }}>Signed URL Access</h3>
          <p style={{ fontSize: "0.95rem", lineHeight: 1.4 }}>Files are only exposed through time-limited URLs generated by the Lambda API.</p>
        </div>
      </div>

      <div className="static-window-grid neo-window">
        <div className="neo-window-header" style={{ backgroundColor: "var(--color-secondary)" }}>
          <span>NEOVAULT // SYS_MONITOR.EXE</span>
          <div className="neo-window-dots">
            <div className="neo-window-dot red" />
            <div className="neo-window-dot yellow" />
            <div className="neo-window-dot green" />
          </div>
        </div>
        <div className="neo-window-body font-mono" style={{ backgroundColor: "#1e1e1e", color: "#3ad384", padding: 20, fontSize: "0.85rem", overflowX: "auto" }}>
          <div>[INFO] BOOTING STATIC FRONT END...</div>
          <div>[INFO] RESOLVING LAMBDA API BASE URL...</div>
          <div style={{ color: "#ffffff", marginTop: 10 }}>------------------------------------------------------------</div>
          <div>HOSTING: <span style={{ color: "#f6d142" }}>STATIC S3 EXPORT</span></div>
          <div>AUTH: <span style={{ color: "#f6d142" }}>COGNITO + LAMBDA</span></div>
          <div>UPLOADS: <span style={{ color: "#f6d142" }}>PRESIGNED S3 PUT URLS</span></div>
          <div>METADATA: <span style={{ color: "#f6d142" }}>DYNAMODB</span></div>
          <div style={{ color: "#ffffff" }}>------------------------------------------------------------</div>
          <div style={{ color: "#3ad384", marginTop: 10 }}>✅ STATIC UI ACTIVE: all AWS calls are proxied through Lambda.</div>
        </div>
      </div>
    </main>
  );
}
